sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.5
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs

script:
  # Requirements
  - |
    export COMPOSER_VENDOR_DIR="$(composer -n config --global home)/vendor"
    export PATH="${COMPOSER_VENDOR_DIR}/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
      composer global require yoast/phpunit-polyfills
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require squizlabs/php_codesniffer
      composer global require wp-coding-standards/wpcs
      composer global require phpcompatibility/php-compatibility
      composer global require phpcompatibility/phpcompatibility-paragonie
      composer global require phpcompatibility/phpcompatibility-wp
      phpcs --config-set installed_paths "${COMPOSER_VENDOR_DIR}/wp-coding-standards/wpcs,${COMPOSER_VENDOR_DIR}/phpcompatibility/php-compatibility,${COMPOSER_VENDOR_DIR}/phpcompatibility/phpcompatibility-paragonie,${COMPOSER_VENDOR_DIR}/phpcompatibility/phpcompatibility-wp"
    fi
  - phpenv rehash

  # Tests
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
