name: Publish

on:
  release:
    types: [released]

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ github.ref_name }}
          file: "pendhope.zip"
          target: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip

  publish:
    needs: download
    runs-on: ubuntu-latest
    steps:
      - run: "svn co https://plugins.svn.wordpress.org/pendo/"
      - run: "rm -vrf pendo/tags/${{ github.ref_name }}"
      - run: "mkdir pendo/tags/${{ github.ref_name }}"
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: "unzip -ou release.zip -d pendo/tags/${{ github.ref_name }}"
      - run: >-
          cd pendo &&
          svn status &&
          svn add --force tags/${{ github.ref_name }}
      - run: >-
          cd pendo &&
          svn commit
          --username="${WORDPRESS_USER}"
          --password="${WORDPRESS_PASSWORD}"
          -m 'Add ${{ github.ref_name }} from ${{ github.sha }}'
        env:
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          WORDPRESS_USER: holyhope
